publicity.default_entity.*:
  type: config_entity
  label: 'Advertising entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    url:
      type: string
      label: 'Url' 
    ad_id:
      type: string
      label: 'ID of Ad'
    place:
      type: string
      label: 'Place'
    breakpoints:
      type: string
      label: 'Breakpoints'       
